import org.gradle.internal.service.ServiceRegistry
import org.gradle.kotlin.dsl.support.serviceOf
import java.nio.CharBuffer
import kotlin.reflect.full.*

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.9.2/userguide/multi_project_builds.html
 */

rootProject.name = "GradleKotlinUtils"
include("kotlinutils")